# Generated by Django 4.1.5 on 2023-01-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_bill', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('identification', models.IntegerField()),
                ('id_cart', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('identification', models.IntegerField()),
                ('id_book', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id_favorites', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('identification', models.IntegerField()),
                ('id_book', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
