# Generated by Django 4.1.5 on 2023-01-31 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bill_cart_favorites_remove_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 1, 27, 16, 864702)),
        ),
    ]
