# Generated by Django 4.1.5 on 2023-02-01 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_username_user_name_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 21, 23, 44, 165676)),
        ),
    ]
