# Generated by Django 4.1.5 on 2023-02-01 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_cart',
            fields=[
                ('id_item', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('id_cart', models.IntegerField()),
                ('id_book', models.IntegerField()),
                ('count', models.IntegerField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 1, 31, 22, 51, 4, 750282))),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='id_book',
        ),
        migrations.AddField(
            model_name='cart',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 22, 51, 4, 750282)),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='activo', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 22, 51, 4, 750282)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 22, 51, 4, 750282)),
        ),
    ]
