export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const VERIFICAR_USUARIO = 'VERIFICAR_USUARIO';
export const CREAR_USUARIO = 'CREAR_USUARIO';
export const GET_CARRITO = 'GET_CARRITO';


export const OBTENER_BOOK = 'OBTENER_BOOK';
export const CREAR_BOOK = 'CREAR_BOOK';
export const OBTENER_BOOKS = 'OBTENER_BOOKS';
export const ACTUALIZAR_BOOK = 'ACTUALIZAR_BOOK';
export const GET_BOOK_FAVORITES = 'GET_BOOK_FAVORITES';
export const GET_BOOK_ADQUIRIDOS = 'GET_BOOK_ADQUIRIDOS';
